version: "3.9"

services:
  db:
    image: postgres
    container_name: filec_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: filecompressor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata:
